site_name: OVPanel Documentation
site_url: https://github.com/primeZdev/ov-panel
repo_url: https://github.com/primeZdev/ov-panel
repo_name: OV-Panel
nav:
  - Home: index.md
  - Installation:
    - Panel:
      - 🚀 Installation guide: installation/Panel/install.md
      - ⚙️ Configuration: installation/Panel/configuration.md
    - Node:
      - 🚀 Installation guide: installation/Node/install.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/fav.svg
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - assets/stylesheets/theme-overrides.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/primeZdev/ov-panel
      name: GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/ovpanel
      name: Telegram